subClassOf(b0,intersectionOf([p1,q1])).
annotationAssertion('disponte:probability',subClassOf(b0,intersectionOf([p1,q1])),literal('0.6')).
subClassOf(p1,b1).
annotationAssertion('disponte:probability',subClassOf(p1,b1),literal('0.6')).
subClassOf(q1,b1).
annotationAssertion('disponte:probability',subClassOf(q1,b1),literal('0.6')).
subClassOf(b1,intersectionOf([p2,q2])).
annotationAssertion('disponte:probability',subClassOf(b1,intersectionOf([p2,q2])),literal('0.6')).
subClassOf(p2,b2).
annotationAssertion('disponte:probability',subClassOf(p2,b2),literal('0.6')).
subClassOf(q2,b2).
annotationAssertion('disponte:probability',subClassOf(q2,b2),literal('0.6')).
subClassOf(b2,intersectionOf([p3,q3])).
annotationAssertion('disponte:probability',subClassOf(b2,intersectionOf([p3,q3])),literal('0.6')).
subClassOf(p3,b3).
annotationAssertion('disponte:probability',subClassOf(p3,b3),literal('0.6')).
subClassOf(q3,b3).
annotationAssertion('disponte:probability',subClassOf(q3,b3),literal('0.6')).
subClassOf(b3,intersectionOf([p4,q4])).
annotationAssertion('disponte:probability',subClassOf(b3,intersectionOf([p4,q4])),literal('0.6')).
subClassOf(p4,b4).
annotationAssertion('disponte:probability',subClassOf(p4,b4),literal('0.6')).
subClassOf(q4,b4).
annotationAssertion('disponte:probability',subClassOf(q4,b4),literal('0.6')).
