subClassOf(b0,intersectionOf([p1,q1])).
annotationAssertion('disponte:probability',subClassOf(b0,intersectionOf([p1,q1])),literal('0.6')).
subClassOf(p1,b1).
annotationAssertion('disponte:probability',subClassOf(p1,b1),literal('0.6')).
subClassOf(q1,b1).
annotationAssertion('disponte:probability',subClassOf(q1,b1),literal('0.6')).
subClassOf(b1,intersectionOf([p2,q2])).
annotationAssertion('disponte:probability',subClassOf(b1,intersectionOf([p2,q2])),literal('0.6')).
subClassOf(p2,b2).
annotationAssertion('disponte:probability',subClassOf(p2,b2),literal('0.6')).
subClassOf(q2,b2).
annotationAssertion('disponte:probability',subClassOf(q2,b2),literal('0.6')).
subClassOf(b2,intersectionOf([p3,q3])).
annotationAssertion('disponte:probability',subClassOf(b2,intersectionOf([p3,q3])),literal('0.6')).
subClassOf(p3,b3).
annotationAssertion('disponte:probability',subClassOf(p3,b3),literal('0.6')).
subClassOf(q3,b3).
annotationAssertion('disponte:probability',subClassOf(q3,b3),literal('0.6')).
subClassOf(b3,intersectionOf([p4,q4])).
annotationAssertion('disponte:probability',subClassOf(b3,intersectionOf([p4,q4])),literal('0.6')).
subClassOf(p4,b4).
annotationAssertion('disponte:probability',subClassOf(p4,b4),literal('0.6')).
subClassOf(q4,b4).
annotationAssertion('disponte:probability',subClassOf(q4,b4),literal('0.6')).
subClassOf(b4,intersectionOf([p5,q5])).
annotationAssertion('disponte:probability',subClassOf(b4,intersectionOf([p5,q5])),literal('0.6')).
subClassOf(p5,b5).
annotationAssertion('disponte:probability',subClassOf(p5,b5),literal('0.6')).
subClassOf(q5,b5).
annotationAssertion('disponte:probability',subClassOf(q5,b5),literal('0.6')).
subClassOf(b5,intersectionOf([p6,q6])).
annotationAssertion('disponte:probability',subClassOf(b5,intersectionOf([p6,q6])),literal('0.6')).
subClassOf(p6,b6).
annotationAssertion('disponte:probability',subClassOf(p6,b6),literal('0.6')).
subClassOf(q6,b6).
annotationAssertion('disponte:probability',subClassOf(q6,b6),literal('0.6')).
subClassOf(b6,intersectionOf([p7,q7])).
annotationAssertion('disponte:probability',subClassOf(b6,intersectionOf([p7,q7])),literal('0.6')).
subClassOf(p7,b7).
annotationAssertion('disponte:probability',subClassOf(p7,b7),literal('0.6')).
subClassOf(q7,b7).
annotationAssertion('disponte:probability',subClassOf(q7,b7),literal('0.6')).
subClassOf(b7,intersectionOf([p8,q8])).
annotationAssertion('disponte:probability',subClassOf(b7,intersectionOf([p8,q8])),literal('0.6')).
subClassOf(p8,b8).
annotationAssertion('disponte:probability',subClassOf(p8,b8),literal('0.6')).
subClassOf(q8,b8).
annotationAssertion('disponte:probability',subClassOf(q8,b8),literal('0.6')).
